version: '3.9'
networks:
    elympics:
        driver: bridge

services: 
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=root
      - POSTGRES_DB=elympics
    restart: always
    ports:
      - '5432:5432'
    volumes:
        - postgres-data:/var/lib/postgresql/data
    networks:
        - elympics
        
  golang-service:
    build:
      context: './goservice'
      dockerfile: 'Dockerfile'
    image: 'corey773/elympics-golang:latest'
    ports:
      - '8000:8000'
    networks:
        - elympics
        
  dotnet-service:
    build:
      context: './dotnetservice'
      dockerfile: 'Dockerfile'
    image: 'corey773/elympics-dotnet:latest'
    ports:
      - '8001:8001'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8001
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=elympics;Username=root;Password=secret
      - GolangServiceConfig__Url=http://golang-service:8000
    depends_on: 
        - postgres
        - golang-service
    networks:
        - elympics
        
volumes:
  postgres-data:
      