apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-api
  namespace: elympics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-api
  template:
    metadata:
      labels:
        app: dotnet-api
    spec:
      containers:
      - name: dotnet-api
        image: corey773/elympics-dotnet:latest
        ports:
        - containerPort: 8001
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://*:8001"
        - name: GolangServiceConfig__Url
          value: 'http://golang-api-service:8000'
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: connection-string

---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-api-service
  namespace: elympics
spec:
  selector:
    app: dotnet-api
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
    nodePort: 30000