apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-api
  namespace: elympics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-api
  template:
    metadata:
      labels:
        app: golang-api
    spec:
      containers:
      - name: golang-api
        image: corey773/elympics-golang:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: golang-api-service
  namespace: elympics
spec:
  selector:
    app: golang-api
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
