apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: elympics
type: Opaque
data:
  username: cm9vdA==
  password: c2VjcmV0
  connection-string: SG9zdD1wb3N0Z3Jlcy1zZXJ2aWNlO1BvcnQ9NTQzMjtEYXRhYmFzZT1lbHltcGljcztVc2VybmFtZT1yb290O1Bhc3N3b3JkPXNlY3JldA==