


apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.fullname" . }}-postgres-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.postgres.username | b64enc | quote }}
  password: {{ .Values.postgres.password | b64enc | quote }}
  connection-string: {{ $conn := printf "Host=%s-postgres-service;Port=%d;Database=%s;User Id=%s;Password=%s;" (include "helm-chart.fullname" .) (.Values.postgres.port | int64) .Values.postgres.dbName .Values.postgres.username .Values.postgres.password }}{{ $conn | b64enc | quote}}
  