name: run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    
  steps:
    - uses: actions/checkout@v3
        
    - name: install dotnet-sdk
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        
    - name: test
      run: |
          cd dotnetservice
          dotnet test
            
      
      
      