name: run tests, build images and push to docker hub

on:
  push:
    branches: [ master ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
          
      - name: install dotnet-sdk
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
          
      - name: test
        run: |
            cd dotnetservice
            dotnet test WebApi.IntegrationTests/WebApi.IntegrationTests.csproj
  
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
          
      - name: install docker
        uses: docker/setup-docker@v1
        
      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build images from docker-compose
        run: |
            docker-compose build
            docker-compose push
        
  

      
      
